MerchandiseShop.WebApp/Controllers/OrdersController.cs
using AutoMapper;
using MerchandiseShop.Application.Orders.Commands.UpdateOrderStatus;
using MerchandiseShop.Application.Orders.Queries.GetOrderDetails;
using MerchandiseShop.Application.Orders.Queries.GetOrderList;
using MerchandiseShop.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MerchandiseShop.WebApp.Controllers
{
    public class OrdersController : BaseController
    {
        private readonly IMapper _mapper;

        public OrdersController(IMapper mapper)
        {
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var query = new GetOrderListQuery();
            var list = await Mediator.Send(query);
            return View("Index", list);
        }

        public async Task<IActionResult> Details(Guid orderId)
        {
            var query = new GetOrderDetailsQuery
            {
                Id = orderId
            };
            var order = await Mediator.Send(query);
            var orderDto = _mapper.Map<OrderDto>(order);
            return View("Details", orderDto);
        }

        public async Task<IActionResult> UpdateStatus(Guid orderId, int statusId)
        {
            var command = new UpdateOrderStatusCommand
            {
                Id = orderId,
                StatusId = statusId
            };
            var orderDetailsVm = await Mediator.Send(command);
            var orderDto = _mapper.Map<OrderDto>(orderDetailsVm);
            return View("Details", orderDto);
        }
    }
}

MerchandiseShop.WebApp/Views/Orders/Details.cshtml
@using MerchandiseShop.Domain.Models
@using MerchandiseShop.Domain.Order
@model MerchandiseShop.WebApp.Models.OrderDto

@{
    ViewData["Title"] = "Details";
}

<div>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
            @{
                var userName = Model.User.FirstName + " " + Model.User.LastName;
            }
            @Html.DisplayFor(model => userName)
        </dd>

        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class="col-sm-10">
            @{
                var dateCreation = Model.DateCreation.ToShortDateString();
            }
            @Html.DisplayFor(model => dateCreation)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCompletion)
        </dt>
        <dd class="col-sm-10">
            @{
                var dateCompletion = "";
                if(Model.DateCompletion != null){
                    dateCompletion = ((DateTime)Model.DateCompletion).ToShortDateString();
                }
            }
            @Html.DisplayFor(model => dateCompletion)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderSum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderSum)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class="col-sm-10">
            @{
                var status = Enumeration.GetAll<OrderStatus>().FirstOrDefault(s => s.Id == Model.StatusId).Name;
            }
            @Html.DisplayFor(model => status)
        </dd>

        @if(Model.StatusId == OrderStatus.InWork.Id)
        {
            <h4>Изменить статус</h4>
            <dt class="col-sm-10">
                <a asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Ready.Id" class="btn btn-primary">Готово к выдаче</a>
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.WaitingNewSupply.Id" class="btn btn-primary">Ожидает новой поставки</a>
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Canceled.Id" class="btn btn-primary">Отменить</a>
            </dt>
        }else if(Model.StatusId == OrderStatus.WaitingNewSupply.Id)
        {
            <h4>Изменить статус</h4>
            <dt class="col-sm-10">
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Ready.Id" class="btn btn-primary">Готово к выдаче</a>
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Canceled.Id" class="btn btn-primary">Отменить</a>
            </dt>
        }else if(Model.StatusId == OrderStatus.Ready.Id)
        {
            <h4>Изменить статус</h4>
            <dt class="col-sm-10">
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Complete.Id" class="btn btn-primary">Получено</a>
                <a asp-controller="Orders" asp-action="UpdateStatus" asp-route-orderId="@Model.Id" asp-route-statusId="@OrderStatus.Canceled.Id" class="btn btn-primary">Отменить</a>
            </dt>
        }

        <h4>Состав заказа</h4>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Товар
                </th>
                <th>
                    Цвет
                </th>
                <th>
                    Размер
                </th>
                <th>
                    Количество
                </th>
                <th>
                    Цена
                </th>
            </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductColor.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.ProductSize.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>
        }
    </tbody>
    </table>


</div>
<div>
    <a asp-action="Index">Назад</a>
</div>

MerchandiseShop.WebApp/Views/Orders/Index.cshtml
@using MerchandiseShop.Domain.Models
@using MerchandiseShop.Domain.Order
@model MerchandiseShop.Application.Orders.Queries.GetOrderList.OrderListVm

@{
    ViewData["Title"] = "Index";
}


<h1>Заказы</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Пользователь
            </th>
            <th>
                Статус
            </th>
            <th>
                Дата создания
            </th>
            <th>
                Дата выполнения
            </th>
            <th>
                Кол-во позиций
            </th>
            <th>
                Сумма
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Orders)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td>
                    @{
                        var status = Enumeration.GetAll<OrderStatus>().FirstOrDefault(s => s.Id == item.StatusId).Name;
                    }
                    @Html.DisplayFor(modelItem => status)
                </td>
                <td>
                    @{
                        var dateCreation = item.DateCreation.ToShortDateString();
                    }
                    @Html.DisplayFor(modelItem => dateCreation)
                </td>
                <td>
                    @{
                        var dateCompletion = "";
                        if(item.DateCompletion != null){
                            dateCompletion = ((DateTime)item.DateCompletion).ToShortDateString();
                        }
                    }
                    @Html.DisplayFor(modelItem => dateCompletion)
                </td>
                <td>
                    @{
                        var quantity = 0;
                        foreach(var orderItem in item.OrderItems)
                        {
                            quantity += orderItem.Quantity;
                        }
                    }
                    @Html.DisplayFor(modelItem => quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderSum)
                </td>
                <td>
                    <a asp-action="Details" asp-route-orderId="@item.Id">Просмотр</a>
                </td>
            </tr>
        }
    </tbody>
</table>