MerchandiseShop.WebApp/Controllers/EventRolesController.cs
using AutoMapper;
using MerchandiseShop.Application.EventRoles.Commands.CreateEventRole;
using MerchandiseShop.Application.EventRoles.Commands.DeleteEventRole;
using MerchandiseShop.Application.EventRoles.Commands.UpdateEventRole;
using MerchandiseShop.Application.EventRoles.Queries.GetEventRoleDetails;
using MerchandiseShop.Application.EventRoles.Queries.GetEventRoleList;
using MerchandiseShop.Domain.Models;
using MerchandiseShop.Domain.Users;
using MerchandiseShop.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MerchandiseShop.WebApp.Controllers
{
    public class EventRolesController : BaseController
    {
        private readonly IMapper _mapper;

        public EventRolesController(IMapper mapper)
        {
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(Guid eventId)
        {
            var query = new GetEventRoleListQuery()
            {
                EventId = eventId
            };
            var list = await Mediator.Send(query);
            return View("Index", list);
        }

        public IActionResult Create(Guid eventId)
        {
            var vm = new EventRoleDto
            {
                EventId = eventId
            };

            var types = Enumeration.GetAll<UserType>().ToList();
            ViewData["UserTypeId"] = new SelectList(types, "Id", "Name");

            return View("Create", vm);
        }

        [HttpPost]
        public async Task<ActionResult<Guid>> Create(EventRoleDto eventRoleDto)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<CreateEventRoleCommand>(eventRoleDto);
                var eventRoleId = await Mediator.Send(command);
                return RedirectToAction(nameof(Index), new { eventId = eventRoleDto.EventId });
            }

            var types = Enumeration.GetAll<UserType>().ToList();
            ViewData["UserTypeId"] = new SelectList(types, "Id", "Name");

            return View("Create", eventRoleDto);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var query = new GetEventRoleDetailsQuery
            {
                Id = id.Value
            };
            var eventRoleDetails = await Mediator.Send(query);
            var eventRoleDto = _mapper.Map<EventRoleDto>(eventRoleDetails);

            var types = Enumeration.GetAll<UserType>().ToList();
            ViewData["UserTypeId"] = new SelectList(types, "Id", "Name");

            return View("Edit", eventRoleDto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EventRoleDto eventRoleDto)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<UpdateEventRoleCommand>(eventRoleDto);
                await Mediator.Send(command);
                return RedirectToAction(nameof(Index), new { eventId = eventRoleDto.EventId });
            }

            var types = Enumeration.GetAll<UserType>().ToList();
            ViewData["UserTypeId"] = new SelectList(types, "Id", "Name");

            return View("Edit", eventRoleDto);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var query = new GetEventRoleDetailsQuery
            {
                Id = id.Value
            };
            var eventRoleDetails = await Mediator.Send(query);
            if (eventRoleDetails == null)
            {
                return NotFound();
            }

            var eventRoleDto = _mapper.Map<EventRoleDto>(eventRoleDetails);

            return View("Delete", eventRoleDto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id, Guid eventId)
        {
            var command = new DeleteEventRoleCommand
            {
                Id = id
            };
            await Mediator.Send(command);
            return RedirectToAction(nameof(Index), new { eventId = eventId });
        }
    }
}

MerchandiseShop.WebApp/Controllers/EventsController.cs
using AutoMapper;
using MerchandiseShop.Application.Events.Commands.CreateEvent;
using MerchandiseShop.Application.Events.Commands.DeleteEvent;
using MerchandiseShop.Application.Events.Commands.UpdateEvent;
using MerchandiseShop.Application.Events.Queries.GetEventDetails;
using MerchandiseShop.Application.Events.Queries.GetEventList;
using MerchandiseShop.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MerchandiseShop.WebApp.Controllers
{
    public class EventsController : BaseController
    {
        private readonly IMapper _mapper;

        public EventsController(IMapper mapper)
        {
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var query = new GetEventListQuery();
            var list = await Mediator.Send(query);
            return View("Index", list);
        }

        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<ActionResult<Guid>> Create(EventDto eventDto)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<CreateEventCommand>(eventDto);
                var eventId = await Mediator.Send(command);
                return RedirectToAction(nameof(Index));
            }
            return View("Create", eventDto);
        }


        [HttpPost]
        public ActionResult AddAvalibleFor(EventDto eventDto)
        {
            if (eventDto.NewAvalibleFor != null || eventDto.NewAvalibleFor != string.Empty)
            {
                eventDto.AvalibleFor.Add(eventDto.NewAvalibleFor);
                eventDto.NewAvalibleFor = string.Empty;
            }
            if(eventDto.Id == Guid.Empty)
            {
                return View("Create", eventDto);
            }
            else
            {
                return View("Edit", eventDto);
            }
        }

        [HttpPost]
        public ActionResult DeleteAvalibleFor(EventDto eventDto, int index)
        {
            eventDto.AvalibleFor.RemoveAt(index);
            if (eventDto.Id == Guid.Empty)
            {
                return View("Create", eventDto);
            }
            else
            {
                return View("Edit", eventDto);
            }
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var query = new GetEventDetailsQuery
            {
                Id = id.Value
            };
            var eventDetails = await Mediator.Send(query);
            var eventDto = _mapper.Map<EventDto>(eventDetails);

            return View("Edit", eventDto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EventDto eventDto)
        {
            if (ModelState.IsValid)
            {
                var command = _mapper.Map<UpdateEventCommand>(eventDto);
                await Mediator.Send(command);
                return RedirectToAction(nameof(Index));
            }

            return View("Edit", eventDto);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var query = new GetEventDetailsQuery
            {
                Id = id.Value
            };
            var eventDetails = await Mediator.Send(query);
            if (eventDetails == null)
            {
                return NotFound();
            }

            var eventDto = _mapper.Map<EventDto>(eventDetails);

            return View("Delete", eventDto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var command = new DeleteEventCommand
            {
                Id = id
            };
            await Mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }
    }
}

MerchandiseShop.WebApp/Views/EventRoles/Create.cshtml
@model MerchandiseShop.WebApp.Models.EventRoleDto

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserTypeId" class="control-label"></label>
                <select asp-for="UserTypeId" class="form-control" asp-items="ViewBag.UserTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Prize" class="control-label"></label>
                <input asp-for="Prize" class="form-control" type="textarea"/>
                <span asp-validation-for="Prize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" style="margin-top:2%" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-eventId="@Model.EventId">Назад</a>
</div>

MerchandiseShop.WebApp/Views/EventRoles/Delete.cshtml
@model MerchandiseShop.WebApp.Models.EventRoleDto

@{
    ViewData["Title"] = "Delete";
}

<h3>Действительно удалить?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" asp-route-eventId="@Model.EventId" /> |
        <a asp-action="Index" asp-route-eventId="@Model.EventId">Назад</a>
    </form>
</div>

MerchandiseShop.WebApp/Views/EventRoles/Edit.cshtml
@model MerchandiseShop.WebApp.Models.EventRoleDto

@{
    ViewData["Title"] = "Edit";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
            </div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserTypeId" class="control-label"></label>
                <select asp-for="UserTypeId" class="form-control" asp-items="ViewBag.UserTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Prize" class="control-label"></label>
                <input asp-for="Prize" class="form-control" type="textarea"/>
                <span asp-validation-for="Prize" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" style="margin-top:2%" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-eventId="@Model.EventId">Назад</a>
</div>

MerchandiseShop.WebApp/Views/EventRoles/Index.cshtml
@using MerchandiseShop.Domain.Models
@using MerchandiseShop.Domain.Users
@model MerchandiseShop.Application.EventRoles.Queries.GetEventRoleList.EventRoleListVm

@{
    ViewData["Title"] = "Index";
}


<h1>Роли мероприятия</h1>

<p>
    <a asp-action="Create" asp-route-eventId="@Model.EventId">Добавить роль</a>
</p>
<div>
    <a asp-action="Index" asp-controller="Events">Назад</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Тип пользователя
            </th>
            <th>
                Приз
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.EventRoles)
        {
            var userType = Enumeration.GetAll<UserType>().FirstOrDefault(u => u.Id == item.UserTypeId);
            if (userType != null)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => userType.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prize)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>